version: '3.9'

services:
  postgres:
    image: postgres:18
    container_name: olist_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: olist_db
    ports:
      - "5433:5432"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./database/security.sql:/docker-entrypoint-initdb.d/2-security.sql
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
